using FluentValidation.Results;

namespace MediatRApi.ApplicationCore.Common.Exceptions;

public class ValidationException : Exception
{
    public ValidationException()
        : base("Se han producido uno o más errores de validación.")
    {
        Errors = new Dictionary<string, string[]>();
    }

    public ValidationException(IEnumerable<ValidationFailure> failures)
        : this()
    {
        Errors = failures
            .GroupBy(e => e.PropertyName, e => e.ErrorMessage)
            .ToDictionary(failureGroup => failureGroup.Key, failureGroup => failureGroup.ToArray());
    }

    public Dictionary<string, string[]> Errors { get; private set; }
}